import Head from "next/head";
//graphql
import { useQuery } from "urql";
import { queryProducts } from "../libs/query";
//components..
import Product from "../components/Product";
export default function Home() {
  //Fetching the data...
  const [results] = useQuery({ query: queryProducts });
  const { data, fetching, error } = results;
  //extracting the products
  const products = data?.products.data;
  const mappedProducts =
    products &&
    products.map(({ attributes: { title, price, slug, image } }) => (
      <Product
        title={title}
        price={price}
        key={slug}
        image={image}
        slug={slug}
      />
    ));
  // console.log(products);
  //Errors and fetching states..
  if (fetching) return <p>Loading....</p>;
  if (error) return <p>Oh no!!! Error fetching data.. </p>;
  //return statements...

  return (
    <div>
      <Head>
        <title>E-Commerce Web App...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Data </h1>
      <Product />
      {mappedProducts}
    </div>
  );
}
